[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.89.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sdd/spatial-bench"

[workspace.dependencies]
spatial-bench-core = { path = "crates/spatial-bench-core", version = "0.1.0" }
blake3 = "1"
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9"
