//! Materialising and building a generated driver.
//!
//! The generated `main.rs` needs a package around it: one that depends on the
//! engine's driver crate and on the library under test. The driver crate itself
//! carries no dependency on any subject — every reference to one lives inside a
//! macro body and expands here — which is what lets a build be pointed at a
//! pinned ref or a working tree without anything hardcoding a path.

use crate::codegen::Generated;
use std::path::{Path, PathBuf};

/// Where a subject's source comes from for one build.
#[derive(Clone, Debug)]
pub enum SubjectSource {
    /// A working tree. Results are marked as such: they record a checkout, not
    /// a revision, so the dataset can reject them.
    Path(PathBuf),
    Git {
        repo: String,
        reference: String,
    },
}

#[derive(Clone, Debug)]
pub struct BuildRequest {
    pub subject: String,
    /// Engine crate providing the macro and harness runtime.
    pub driver_crate: String,
    pub driver_crate_path: PathBuf,
    pub subject_crate: String,
    pub subject_source: SubjectSource,
    pub features: Vec<String>,
    pub rustflags: Option<String>,
    pub generated: Generated,
}

/// Write the package for a generated driver and return its directory.
///
/// Keyed by the cache key, so an identical selection reuses a directory and
/// cargo's own incremental state. Nothing here is a source file: the whole tree
/// is engine output.
pub fn materialise(root: &Path, request: &BuildRequest) -> Result<PathBuf, BuildError> {
    let dir = root
        .join(&request.subject)
        .join(&request.generated.cache_key);
    std::fs::create_dir_all(dir.join("src")).map_err(|e| BuildError::Io {
        path: dir.clone(),
        err: e.to_string(),
    })?;

    let subject_dep = match &request.subject_source {
        SubjectSource::Path(p) => {
            format!(
                "{{ path = {:?}, features = {:?} }}",
                p.display().to_string(),
                request.features
            )
        }
        SubjectSource::Git { repo, reference } => format!(
            "{{ git = {repo:?}, rev = {reference:?}, features = {:?} }}",
            request.features
        ),
    };

    let manifest = format!(
        "# Generated by spatial-bench. Do not edit; this whole directory is output.\n\
         [package]\n\
         name = \"spatial-bench-generated\"\n\
         version = \"0.0.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\n\
         [[bin]]\n\
         name = \"driver\"\n\
         path = \"src/main.rs\"\n\n\
         [dependencies]\n\
         {driver} = {{ path = {driver_path:?} }}\n\
         {subject} = {subject_dep}\n\n\
         [profile.release]\n\
         # Benchmarks are meaningless below the optimisation level they ship at.\n\
         opt-level = 3\n\
         debug = true\n",
        driver = request.driver_crate,
        driver_path = request.driver_crate_path.display().to_string(),
        subject = request.subject_crate,
    );

    write_if_changed(&dir.join("Cargo.toml"), &manifest)?;
    write_if_changed(&dir.join("src/main.rs"), &request.generated.source)?;
    Ok(dir)
}

/// Only touch a file whose content differs, so cargo's mtime-based staleness
/// check does not force a rebuild of an unchanged package.
fn write_if_changed(path: &Path, content: &str) -> Result<(), BuildError> {
    if let Ok(existing) = std::fs::read_to_string(path) {
        if existing == content {
            return Ok(());
        }
    }
    std::fs::write(path, content).map_err(|e| BuildError::Io {
        path: path.to_owned(),
        err: e.to_string(),
    })
}

#[derive(Debug)]
pub enum BuildError {
    Io { path: PathBuf, err: String },
    Cargo { status: Option<i32>, stderr: String },
    Spawn(String),
}

impl std::fmt::Display for BuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BuildError::Io { path, err } => write!(f, "{}: {err}", path.display()),
            BuildError::Cargo { status, stderr } => {
                write!(f, "cargo exited with {status:?}\n{stderr}")
            }
            BuildError::Spawn(e) => write!(f, "could not run cargo: {e}"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::Generated;

    fn request(source: SubjectSource) -> BuildRequest {
        BuildRequest {
            subject: "kiddo_v6".into(),
            driver_crate: "spatial-bench-kiddo-v6".into(),
            driver_crate_path: PathBuf::from("/engine/crates/spatial-bench-kiddo-v6"),
            subject_crate: "kiddo".into(),
            subject_source: source,
            features: vec!["test_utils".into()],
            rustflags: None,
            generated: Generated {
                source: "fn main() {}\n".into(),
                cache_key: "abc123".into(),
                combinations: 1,
            },
        }
    }

    #[test]
    fn writes_a_package_keyed_by_the_cache_key() {
        let tmp = std::env::temp_dir().join(format!("sb-build-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let dir = materialise(&tmp, &request(SubjectSource::Path("/w/kiddo".into()))).unwrap();

        assert!(dir.ends_with("kiddo_v6/abc123"));
        let manifest = std::fs::read_to_string(dir.join("Cargo.toml")).unwrap();
        assert!(manifest.contains(r#"kiddo = { path = "/w/kiddo""#));
        assert!(
            manifest.contains("opt-level = 3"),
            "an unoptimised benchmark is meaningless"
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("src/main.rs")).unwrap(),
            "fn main() {}\n"
        );
        std::fs::remove_dir_all(&tmp).ok();
    }

    #[test]
    fn a_git_source_is_pinned_by_revision() {
        let tmp = std::env::temp_dir().join(format!("sb-build-git-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let dir = materialise(
            &tmp,
            &request(SubjectSource::Git {
                repo: "https://github.com/sdd/kiddo".into(),
                reference: "v6.0.0-alpha.4".into(),
            }),
        )
        .unwrap();
        let manifest = std::fs::read_to_string(dir.join("Cargo.toml")).unwrap();
        assert!(manifest.contains(r#"rev = "v6.0.0-alpha.4""#));
        std::fs::remove_dir_all(&tmp).ok();
    }

    /// Rewriting an identical file would bump its mtime and force cargo to
    /// rebuild a package that has not changed.
    #[test]
    fn an_unchanged_package_is_not_rewritten() {
        let tmp = std::env::temp_dir().join(format!("sb-build-idem-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        let req = request(SubjectSource::Path("/w/kiddo".into()));
        let dir = materialise(&tmp, &req).unwrap();
        let before = std::fs::metadata(dir.join("src/main.rs"))
            .unwrap()
            .modified()
            .unwrap();
        std::thread::sleep(std::time::Duration::from_millis(20));
        materialise(&tmp, &req).unwrap();
        let after = std::fs::metadata(dir.join("src/main.rs"))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(before, after);
        std::fs::remove_dir_all(&tmp).ok();
    }
}
