//! Generating a two-phase driver's `main.rs`.
//!
//! A library as generic as kiddo cannot have one driver binary that instantiates
//! every combination of scalar, dimensionality, bucket size, index type, stem
//! strategy and leaf strategy — that cross product is what makes its own fuzz
//! binary take an age to compile. So the engine emits one macro invocation per
//! combination the selection actually needs.
//!
//! Two properties are requirements rather than niceties:
//!
//! - **Deterministic.** The same selection always produces byte-identical
//!   source. Without that the build cache cannot work at all.
//! - **Content-keyed.** The cache key covers the source, the toolchain, the
//!   subject's revision and its features, so a rerun is free but a changed
//!   subject rebuilds.

use crate::case::Case;
use crate::selector::SelectorSet;

/// A generated driver, ready to write to disk and build.
#[derive(Clone, Debug, PartialEq)]
pub struct Generated {
    pub source: String,
    /// Identifies this build. Same key means the binary can be reused.
    pub cache_key: String,
    /// How many monomorphisations the source asks for — the number that decides
    /// compile time, which is why the menu reports it separately from points.
    pub combinations: usize,
}

/// Everything outside the selection that a build depends on.
#[derive(Clone, Debug, Default)]
pub struct BuildInputs {
    pub toolchain: String,
    /// Same source compiled with different flags is a different binary, so this
    /// is part of the key.
    pub rustflags: Option<String>,
    /// Git revision or version of the subject being built.
    pub subject_rev: String,
    pub features: Vec<String>,
}

/// Generate `main.rs` for one subject's driver.
///
/// `cases` should already be filtered to a single subject; the compile-time
/// coordinates are deduplicated here, so cases differing only in runtime axes
/// collapse into one invocation.
pub fn generate(
    driver_crate: &str,
    macro_name: &str,
    subject: &str,
    cases: &[&Case],
    inputs: &BuildInputs,
) -> Generated {
    let ns = crate::vocab::namespace_of(subject);
    let prefix = format!("{ns}.");

    let mut combinations: Vec<Vec<(String, String)>> = cases
        .iter()
        .map(|case| {
            let mut pairs: Vec<(String, String)> = case
                .compile_time_key()
                .into_iter()
                // The macro sees bare names: `stem`, not `kiddo.stem`. The
                // namespace exists to keep subjects apart in a shared dataset,
                // and means nothing inside one subject's own driver.
                .map(|(k, v)| (k.strip_prefix(&prefix).unwrap_or(&k).to_owned(), v))
                .collect();
            pairs.sort();
            pairs
        })
        .collect();
    combinations.sort();
    combinations.dedup();

    let crate_ident = driver_crate.replace('-', "_");
    let mut source = String::new();
    source.push_str("// Generated by spatial-bench. Do not edit.\n");
    source.push_str("//\n");
    source.push_str(
        "// One invocation per compile-time combination the selection needs, so\n\
         // build time scales with the selection rather than the catalog.\n\n",
    );
    source.push_str(&format!(
        "use {crate_ident}::{{{macro_name}, harness_main}};\n\n"
    ));
    source.push_str("fn main() -> std::process::ExitCode {\n");
    source.push_str("    harness_main(&[\n");
    for pairs in &combinations {
        let args: Vec<String> = pairs.iter().map(|(k, v)| format!("{k} = {v}")).collect();
        source.push_str(&format!("        {macro_name}!({}),\n", args.join(", ")));
    }
    source.push_str("    ])\n}\n");

    let mut key_material = String::new();
    key_material.push_str(&source);
    key_material.push('\u{1}');
    key_material.push_str(&inputs.toolchain);
    key_material.push('\u{1}');
    key_material.push_str(&inputs.subject_rev);
    key_material.push('\u{1}');
    let mut features = inputs.features.clone();
    features.sort();
    key_material.push_str(&features.join(","));
    key_material.push('\u{1}');
    key_material.push_str(inputs.rustflags.as_deref().unwrap_or(""));

    Generated {
        cache_key: blake3::hash(key_material.as_bytes()).to_hex()[..16].to_owned(),
        combinations: combinations.len(),
        source,
    }
}

/// Cases in a selection grouped by subject, ready to hand to [`generate`].
pub fn by_subject<'a>(
    catalog: &'a crate::catalog::Catalog,
    sel: &SelectorSet,
) -> Vec<(String, Vec<&'a Case>)> {
    let mut groups: std::collections::BTreeMap<String, Vec<&'a Case>> = Default::default();
    for case in catalog.matching(sel) {
        groups.entry(case.subject.clone()).or_default().push(case);
    }
    groups.into_iter().collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn catalog() -> crate::catalog::Catalog {
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../subjects");
        crate::catalog_load::load_dir(&dir).unwrap()
    }

    fn inputs() -> BuildInputs {
        BuildInputs {
            toolchain: "1.89.0".into(),
            rustflags: Some("-C target-cpu=native".into()),
            subject_rev: "v6.0.0-alpha.4".into(),
            features: vec!["simd".into()],
        }
    }

    fn gen_for(sel: &str) -> Generated {
        let catalog = catalog();
        let selection = SelectorSet::parse_all([sel]).unwrap();
        let groups = by_subject(&catalog, &selection);
        let (subject, cases) = groups.into_iter().find(|(s, _)| s == "kiddo_v6").unwrap();
        generate(
            "spatial-bench-kiddo-v6",
            "bench_case",
            &subject,
            &cases,
            &inputs(),
        )
    }

    #[test]
    fn emits_one_invocation_per_combination() {
        // f32 and f64 are separate monomorphisations, so the two axis values
        // are two combinations even though every other generic axis is fixed.
        let generated = gen_for("impl=kiddo_v6,kiddo.stem=eytzinger");
        assert_eq!(generated.combinations, 2);
        assert_eq!(generated.source.matches("bench_case!(").count(), 2);

        // The whole catalog is every generic combination.
        assert_eq!(gen_for("impl=kiddo_v6").combinations, 18);
        assert!(generated.source.contains("use spatial_bench_kiddo_v6::"));
    }

    /// The macro sees bare names. Namespacing exists to keep subjects apart in a
    /// shared dataset and means nothing inside one subject's own driver.
    #[test]
    fn macro_arguments_are_namespace_stripped_and_sorted() {
        let generated = gen_for("impl=kiddo_v6,kiddo.stem=eytzinger");
        let line = generated
            .source
            .lines()
            .find(|l| l.contains("axis = f64"))
            .unwrap()
            .trim();
        assert_eq!(
            line,
            "bench_case!(axis = f64, block_height = 3, bucket = 32, dims = 3, \
             idx = u32, leaf = flatvec, stem = eytzinger),"
        );
        assert!(!generated.source.contains("kiddo."));
    }

    /// The property the whole two-phase design exists for.
    #[test]
    fn runtime_sweeps_do_not_add_combinations() {
        let one = gen_for("impl=kiddo_v6,kiddo.stem=eytzinger,tree_size=2^20");
        let many = gen_for("impl=kiddo_v6,kiddo.stem=eytzinger,tree_size=2^16..2^25");
        assert_eq!(one.combinations, many.combinations);
        assert_eq!(
            one.source, many.source,
            "runtime axes must not reach the source"
        );
        assert_eq!(one.cache_key, many.cache_key, "so the build is reused");
    }

    /// Without byte-identical output for the same selection, caching cannot work.
    #[test]
    fn generation_is_deterministic() {
        assert_eq!(
            gen_for("impl=kiddo_v6,kiddo.stem=eytzinger"),
            gen_for("impl=kiddo_v6,kiddo.stem=eytzinger")
        );
    }

    /// A changed subject revision, toolchain or feature set must rebuild, even
    /// though the generated source is identical.
    #[test]
    fn cache_key_covers_more_than_the_source() {
        let catalog = catalog();
        let selection = SelectorSet::parse_all(["impl=kiddo_v6"]).unwrap();
        let cases: Vec<&Case> = catalog.matching(&selection);

        let base = generate("d", "bench_case", "kiddo_v6", &cases, &inputs());
        for mutate in [
            |i: &mut BuildInputs| i.toolchain = "1.90.0".into(),
            |i: &mut BuildInputs| i.subject_rev = "deadbeef".into(),
            |i: &mut BuildInputs| i.features.push("logging_off".into()),
            |i: &mut BuildInputs| i.rustflags = None,
        ] {
            let mut changed = inputs();
            mutate(&mut changed);
            let other = generate("d", "bench_case", "kiddo_v6", &cases, &changed);
            assert_eq!(other.source, base.source);
            assert_ne!(other.cache_key, base.cache_key);
        }
    }

    /// Feature order must not change the key, or an equivalent build would miss.
    #[test]
    fn feature_order_does_not_change_the_key() {
        let catalog = catalog();
        let selection = SelectorSet::parse_all(["impl=kiddo_v6"]).unwrap();
        let cases: Vec<&Case> = catalog.matching(&selection);
        let mut a = inputs();
        a.features = vec!["simd".into(), "logging_off".into()];
        let mut b = inputs();
        b.features = vec!["logging_off".into(), "simd".into()];
        assert_eq!(
            generate("d", "bench_case", "kiddo_v6", &cases, &a).cache_key,
            generate("d", "bench_case", "kiddo_v6", &cases, &b).cache_key
        );
    }

    /// nanoflann declares no compile-time keys, so it generates a single
    /// invocation with no arguments — single-phase subjects are not a special
    /// case in the generator.
    #[test]
    fn a_subject_with_no_generic_axes_still_generates() {
        let catalog = catalog();
        let selection = SelectorSet::default();
        let (subject, cases) = by_subject(&catalog, &selection)
            .into_iter()
            .find(|(s, _)| s == "nanoflann")
            .unwrap();
        let generated = generate("d", "bench_case", &subject, &cases, &inputs());
        assert_eq!(generated.combinations, 1);
        assert!(generated.source.contains("bench_case!(),"));
    }
}
