name: CI / Common

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ci-common-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  commitlint:
    name: Commit Lint
    if: github.event_name != 'pull_request' || github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v7
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.yaml

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false

      - name: Install `stable` Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Install taplo
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli

      - name: Cargo fmt check
        run: cargo fmt --all --check

      - name: Toml format check
        run: taplo format --check ./*.toml

      - name: Check Rustdoc Links
        run: RUSTDOCFLAGS="--deny broken_intra_doc_links" cargo doc --verbose --workspace --no-deps --document-private-items

  github-actions-lint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          show-progress: false

      - name: Lint GitHub Actions workflows
        uses: docker://rhysd/actionlint:latest
